import type { PlanningTask } from './types';

const now = '2026-06-16T00:00:00.000Z';

export const defaultPlanningTasks: PlanningTask[] = [
  {
    id: 'blog-reunion-editorial',
    title: 'Alimenter la page blog avec des articles sur La Réunion',
    description:
      'Préparer une ligne éditoriale autour des recettes, de la culture, des communes, des événements et des idées cadeaux péi.',
    status: 'todo',
    priority: 'high',
    category: 'blog',
    dueDate: '',
    publishDate: '',
    budget: 'Temps de rédaction',
    feasibility: '',
    link: '/admin/blog',
    checklist: [
      { id: 'blog-1', label: 'Lister 10 sujets prioritaires', done: false },
      { id: 'blog-2', label: 'Définir un rythme de publication', done: false },
      { id: 'blog-3', label: 'Préparer les visuels', done: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gift-card-site',
    title: 'Créer une carte cadeau pour le site',
    description:
      'Proposer une carte cadeau Island Dreams utilisable en boutique. Budget illimité pour définir la meilleure expérience client.',
    status: 'idea',
    priority: 'medium',
    category: 'product',
    dueDate: '',
    publishDate: '',
    budget: 'Budget illimité',
    feasibility: 'À cadrer : montant libre ou montants prédéfinis, code promo, email automatique.',
    link: '',
    checklist: [
      { id: 'gift-card-1', label: 'Définir les montants', done: false },
      { id: 'gift-card-2', label: 'Définir le fonctionnement checkout', done: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'run-map-3d-magnets',
    title: 'Étudier le concept carte RUN 3D avec emplacements magnets',
    description:
      'Carte 50 x 50 cm, relief max 2,5 cm. Emplacements magnets 50 mm pour magnets 45 mm, aimantés. Trou central 1 cm de diamètre sur 4 mm de profondeur. Option découpe en 4 parties de 25 x 25 cm, emboîtées façon puzzle ou aimantées pour faciliter l’envoi en France.',
    status: 'idea',
    priority: 'high',
    category: '3d',
    dueDate: '',
    publishDate: '',
    budget: 'Prototype à chiffrer',
    feasibility:
      'À valider : poids, matière, assemblage, aimants, coût impression 3D/CNC, packaging, transport.',
    link: '',
    checklist: [
      { id: 'run-map-1', label: 'Faire un croquis technique', done: false },
      { id: 'run-map-2', label: 'Demander faisabilité fabrication', done: false },
      { id: 'run-map-3', label: 'Comparer puzzle vs aimants', done: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'collector-box-3d',
    title: 'Créer une boîte collector 3D pour les magnets',
    description:
      'Imaginer une boîte collector pour ranger/offrir les magnets Island Dreams, avec design péi et format pratique.',
    status: 'idea',
    priority: 'medium',
    category: '3d',
    dueDate: '',
    publishDate: '',
    budget: 'Prototype à chiffrer',
    feasibility: 'À définir : nombre de magnets, matière, fermeture, coût unitaire.',
    link: '',
    checklist: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gift-25-order',
    title: 'Offrir un cadeau dès 25 € d’achat',
    description:
      'Mettre en avant un cadeau automatique, par exemple un porte-clés, dès 25 € d’achat.',
    status: 'doing',
    priority: 'high',
    category: 'site',
    dueDate: '',
    publishDate: '',
    budget: 'Coût produit offert',
    feasibility: 'Fonction cadeau automatique déjà présente, vérifier le seuil configuré en admin.',
    link: '/admin/parametres',
    checklist: [
      { id: 'gift-25-1', label: 'Configurer le seuil à 25 €', done: false },
      { id: 'gift-25-2', label: 'Vérifier affichage panier et checkout', done: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'blog-francofolies',
    title: 'Créer un article sur l’événement du moment : Francofolies',
    description:
      'Article blog autour des Francofolies : événement, ambiance, idées souvenirs, produits à mettre en avant.',
    status: 'todo',
    priority: 'high',
    category: 'event',
    dueDate: '',
    publishDate: '',
    budget: 'Temps de rédaction',
    feasibility: '',
    link: '/admin/blog/nouveau',
    checklist: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'blog-fete-peres',
    title: 'Créer un article fête des pères + cadeau joint à une commande',
    description:
      'Article blog et opération commerciale fête des pères avec proposition de cadeau ajouté à la commande.',
    status: 'todo',
    priority: 'high',
    category: 'blog',
    dueDate: '',
    publishDate: '',
    budget: 'Coût cadeau',
    feasibility: '',
    link: '/admin/blog/nouveau',
    checklist: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'logo-keychain-3d',
    title: 'Tester le logo Island Dreams en porte-clés et en 3D',
    description:
      'Préparer des essais du logo Island Dreams pour porte-clés, objet 3D et éventuellement une figurine.',
    status: 'idea',
    priority: 'medium',
    category: '3d',
    dueDate: '',
    publishDate: '',
    budget: 'Prototype à chiffrer',
    feasibility: 'À valider : lisibilité du logo, solidité, taille minimale, couleur/matière.',
    link: '',
    checklist: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'pinterest-products',
    title: 'Mettre les produits Island Dreams sur Pinterest',
    description:
      'Créer des épingles produits pour améliorer la visibilité et générer du trafic vers la boutique.',
    status: 'todo',
    priority: 'medium',
    category: 'marketing',
    dueDate: '',
    publishDate: '',
    budget: 'Gratuit',
    feasibility: '',
    link: '',
    checklist: [
      { id: 'pin-1', label: 'Créer le compte ou optimiser le profil', done: false },
      { id: 'pin-2', label: 'Préparer 10 visuels produits', done: false },
      { id: 'pin-3', label: 'Ajouter les liens boutique', done: false },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'admin-invoices',
    title: 'Ajouter la facturation dans l’admin pour les commandes clients',
    description:
      'Afficher les factures Stripe et reçus depuis les fiches commandes clients dans l’admin.',
    status: 'done',
    priority: 'medium',
    category: 'admin',
    dueDate: '',
    publishDate: '',
    budget: 'Déjà implémenté',
    feasibility: 'Factures Stripe exposées dans les commandes admin.',
    link: '/admin/commandes',
    checklist: [{ id: 'invoice-1', label: 'Vérifier sur une commande payée', done: false }],
    createdAt: now,
    updatedAt: now,
  },
];
